name: docker-image-test
on:
  workflow_dispatch:

jobs:
  test_sync_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: hhyasdf/image-sync-action@v1.1
        with:
          auth_file: ./auth.yaml
          images_file: ./images.yaml
          version: latest
          proc: 6 # The max number of goroutines to sync images, default value is 5.
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }} # For safty consideration, passing registry password by github action secrets is needed.
          ALIHUB_PASSWORD: ${{ secrets.ALIHUB_PASSWORD }} # For safty consideration, passing registry password by github action secrets is needed.
