name: manual-sync
on:
  workflow_dispatch:
    inputs:
      source:
        description: '镜像名:tag (Docker Hub)'     
        required: true
        default: 'nginx:1.13'
      destination:
        description: '目标源 (Registry)'
        required: true
        default: 'registry.cn-beijing.aliyuncs.com/yt-mirror/nginx'
  
jobs:
  image-sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Check source for image format
      id: check_source
      run: |
        node .github/scripts/check_format.js "${{ github.event.inputs.source }}"
    - name: source is not image format
      if: steps.check_source.outputs.is_image_format == 'false'
      run: |
        echo "请使用标准镜像格式! 镜像要带tag,如nginx,请写为nginx:latest"
      
    - name: start sync
      if: steps.check_source.outputs.is_image_format == 'true'
      run: |
        echo ${{ github.event.inputs.source }}: ${{ github.event.inputs.destination }} > images.yaml
        wget -q  https://github.com/AliyunContainerService/image-syncer/releases/download/v1.5.4/image-syncer-v1.5.4-linux-amd64.tar.gz
        tar zxf image-syncer-v1.5.4-linux-amd64.tar.gz
        cat ./images.yaml

    - name: 执行同步镜像
      if: steps.check_source.outputs.is_image_format == 'true'
      env: 
        ALIHUB_PASSWORD: ${{ secrets.ALIHUB_PASSWORD }}
      run: |
        ./image-syncer --auth=./auth.yaml --images=./images.yaml --retries=2